### ISSUE TITLE
Move Profile Picture Setting to "Personal Information" Section

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#405]
**Description:**

The profile picture setting should be moved to the "Personal Information" section in the settings page. The following changes need to be made:

1. **Relocate Profile Picture Setting:**
   - Move the profile picture setting into the "Personal Information" section.

2. **Update Profile Picture Widget:**
   - Clicking "Update" should display a widget similar to the blue square currently used for drag/drop image or uploading an image.

3. **Remove Image Size Restriction:**
   - There should not be an image size restriction. Instead, the client app should offer options to crop and center the image.

4. **Upload Path for New Profile Image:**
   - The image should be uploaded to the cloud storage at `/tanam-users/{uid}/new-profile-image` without an extension.

### Acceptance Criteria:
- [x] Profile picture setting is relocated to the "Personal Information" section.
- [x] Clicking "Update" displays the appropriate widget for image upload.
- [x] Client app provides options to crop and center the uploaded image.
- [x] The image is uploaded to the specified path without an extension.

![image](https://github.com/user-attachments/assets/51558a74-1bc7-4b88-83fc-41b3625234c5)
