### ISSUE TITLE
Implement Read Only Mode for User Settings

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#418]
## Description

This issue involves implementing a "read only mode" for the user settings form. The form should be in read-only mode by default and switch to "edit mode" when the "edit" button is clicked. When in "edit mode", a "save" and "cancel" button should be displayed. Clicking the "cancel" button should revert any changes and switch the form back to read-only mode.
<img width="548" alt="image" src="https://github.com/user-attachments/assets/c4b9ae7e-3523-4017-96bb-258fd1e80966">

## Tasks

1. Set the user settings form to be in read-only mode by default.
2. Add an "edit" button to switch the form to "edit mode".
3. In "edit mode", display "save" and "cancel" buttons.
4. Ensure the "save" button saves any changes made to the user settings.
5. Ensure the "cancel" button reverts any changes and switches the form back to read-only mode.
6. Ensure the transition between modes is smooth and user-friendly.

## Acceptance Criteria

- [x] The user settings form is in read-only mode by default.
- [x] An "edit" button is present to switch the form to "edit mode".
- [x] In "edit mode", "save" and "cancel" buttons are displayed.
- [x] The "save" button saves any changes made to the user settings.
- [x] The "cancel" button reverts any changes and switches the form back to read-only mode.
- [x] The implementation provides a smooth and user-friendly transition between modes.
